In [2]:
import fastf1
import pandas as pd

In [48]:
sessions_df = pd.read_csv("race_f1_sessions22.csv")
# sessions_df = pd.read_csv("race_f1_sessions23.csv")
# sessions_df = pd.read_csv("race_f1_sessions24.csv")
# sessions_df = pd.read_csv("race_f1_sessions25.csv")

In [49]:
sessions_df['Compound'].unique()

array(['SOFT', 'MEDIUM', 'HARD', 'INTERMEDIATE', 'WET', nan], dtype=object)

In [4]:
sessions_df.columns

Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'FastF1Generated', 'IsAccurate', 'Year', 'Round', 'Session'],
      dtype='object')

In [9]:
max = sessions_df["Round"].max()
print(max)

22

In [5]:
def get_races_for_year(year):
    races = []

    for rnd in range(1, 30):  
        try:
            session = fastf1.get_session(year, rnd, "R")  
            session.load()
            races.append({
                "Year": year,
                "Round": rnd,
                "RaceName": session.event.EventName
            })
        except:
            pass

    return races

races = get_races_for_year(2022)

print(races)

req         WARNING 	DEFAULT CACHE ENABLED! (96.04 KB) C:\Users\onehi\AppData\Local\Temp\fastf1
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.7.0]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core        WARNING 	Driver 16 completed the race distance 00:00.050000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['16', '55', '44', '63', '20', '77', '31', '22', '14', '24', '47', '18', '23', '3', '4', '6', '27', '11', '1', '10']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.7.0]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 22
core        WARNING 	No lap data for driver 47
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 22)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 47)
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '11', '63', '31', '4', '10', '20', '44', '24', '27', '18', '23', '77', '14', '3', '6', '22', '47']
core           INFO 	Loading data for Australian Grand Prix - Race [v3.7.0]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
_api        WARNING 	Driver  3: Ignoring late data for a previously processed lap.The data may contain errors (previous: 28; current 29)
_api        WARNING 	Failed to align laps for drivers: ['55']
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core        WARNING 	Driver 16 completed the race distance 00:00.140000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['16', '11', '63', '44', '4', '3', '31', '77', '10', '23', '24', '18', '47', '20', '22', '6', '14', '1', '5', '55']
core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.7.0]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
_api        WARNING 	Driver 243: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '4', '63', '77', '16', '22', '5', '20', '18', '23', '10', '44', '31', '24', '6', '47', '3', '14', '55']
core           INFO 	Loading data for Miami Grand Prix - Race [v3.7.0]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
_api        WARNING 	Driver 243: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '11', '63', '44', '77', '31', '23', '18', '14', '22', '3', '6', '47', '20', '5', '10', '4', '24']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.7.0]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '63', '55', '44', '77', '31', '4', '14', '22', '5', '3', '10', '47', '18', '6', '20', '23', '24', '16']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.7.0]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '11'
core        WARNING 	Fixed incorrect tyre stint information for driver '55'
core        WARNING 	Fixed incorrect tyre stint information for driver '1'
core        WARNING 	Fixed incorrect tyre stint information for driver '16'
core        WARNING 	Fixed incorrect tyre stint information for driver '63'
core        WARNING 	Fixed incorrect tyre stint information for driver '4'
core        WARNING 	Fixed incorrect tyre stint information for driver '14'
core        WARNING 	Fixed incorrect tyre stint information for driver '44'
core        WARNING 	Fixed incorrect tyre stint information for driver '77'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
core        WARNING 	Fixed incorrect tyre stint information for driver '10'
core        WARNING 	Fixed incorrect tyre stint information for driver '31'
core        WARNING 	Fixed incorrect tyre stint information for driver '3'
core        WARNING 	Fixed incorrect tyre stint information for driver '18'
core        WARNING 	Fixed incorrect tyre stint information for driver '6'
core        WARNING 	Fixed incorrect tyre stint information for driver '24'
core        WARNING 	Fixed incorrect tyre stint information for driver '22'
core        WARNING 	Fixed incorrect tyre stint information for driver '23'
core        WARNING 	Fixed incorrect tyre stint information for driver '47'
core        WARNING 	Fixed incorrect tyre stint information for driver '20'
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
_api        WARNING 	Driver 243: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!

[{'Year': 2022, 'Round': 1, 'RaceName': 'Bahrain Grand Prix'}, {'Year': 2022, 'Round': 2, 'RaceName': 'Saudi Arabian Grand Prix'}, {'Year': 2022, 'Round': 3, 'RaceName': 'Australian Grand Prix'}, {'Year': 2022, 'Round': 4, 'RaceName': 'Emilia Romagna Grand Prix'}, {'Year': 2022, 'Round': 5, 'RaceName': 'Miami Grand Prix'}, {'Year': 2022, 'Round': 6, 'RaceName': 'Spanish Grand Prix'}, {'Year': 2022, 'Round': 7, 'RaceName': 'Monaco Grand Prix'}, {'Year': 2022, 'Round': 8, 'RaceName': 'Azerbaijan Grand Prix'}, {'Year': 2022, 'Round': 9, 'RaceName': 'Canadian Grand Prix'}, {'Year': 2022, 'Round': 10, 'RaceName': 'British Grand Prix'}, {'Year': 2022, 'Round': 11, 'RaceName': 'Austrian Grand Prix'}, {'Year': 2022, 'Round': 12, 'RaceName': 'French Grand Prix'}, {'Year': 2022, 'Round': 13, 'RaceName': 'Hungarian Grand Prix'}, {'Year': 2022, 'Round': 14, 'RaceName': 'Belgian Grand Prix'}, {'Year': 2022, 'Round': 15, 'RaceName': 'Dutch Grand Prix'}, {'Year': 2022, 'Round': 16, 'RaceName': 'Italian Grand Prix'}, {'Year': 2022, 'Round': 17, 'RaceName': 'Singapore Grand Prix'}, {'Year': 2022, 'Round': 18, 'RaceName': 'Japanese Grand Prix'}, {'Year': 2022, 'Round': 19, 'RaceName': 'United States Grand Prix'}, {'Year': 2022, 'Round': 20, 'RaceName': 'Mexico City Grand Prix'}, {'Year': 2022, 'Round': 21, 'RaceName': 'São Paulo Grand Prix'}, {'Year': 2022, 'Round': 22, 'RaceName': 'Abu Dhabi Grand Prix'}]

In [7]:
len(races)

22

In [38]:
# Australian Grand Prix	Australia Albert Park Circuit, Melbourne	10 April
# 4	Emilia Romagna Grand Prix	Italy Imola Circuit, Imola	24 April
# 5	Miami Grand Prix	United States Miami International Autodrome, Miami Gardens, Florida	8 May
# 6	Spanish Grand Prix	Spain Circuit de Barcelona-Catalunya, Montmeló	22 May
# 7	Monaco Grand Prix	Monaco Circuit de Monaco, Monaco	29 May
# 8	Azerbaijan Grand Prix	Azerbaijan Baku City Circuit, Baku	12 June
# 9	Canadian Grand Prix	Canada Circuit Gilles Villeneuve, Montreal	19 June
# 10	British Grand Prix	United Kingdom Silverstone Circuit, Silverstone	3 July
# 11	Austrian Grand Prix	Austria Red Bull Ring, Spielberg	10 July
# 12	French Grand Prix	France Circuit Paul Ricard, Le Castellet	24 July
# 13	Hungarian Grand Prix	Hungary Hungaroring, Mogyoród	31 July
# 14	Belgian Grand Prix	Belgium Circuit de Spa-Francorchamps, Stavelot	28 August
# 15	Dutch Grand Prix	Netherlands Circuit Zandvoort, Zandvoort	4 September
# 16	Italian Grand Prix	Italy Monza Circuit, Monza	11 September
# 17	Singapore Grand Prix	Singapore Marina Bay Street Circuit, Singapore	2 October
# 18	Japanese Grand Prix	Japan Suzuka International Racing Course, Suzuka	9 October
# 19	United States Grand Prix	United States Circuit of the Americas, Austin, Texas	23 October
# 20	Mexico City Grand Prix	Mexico Autódromo Hermanos Rodríguez, Mexico City	30 October
# 21	São Paulo Grand Prix	Brazil Interlagos Circuit, São Paulo	13 November
# 22	Abu Dhabi Grand Prix	United Arab Emirates Yas Marina Circuit, Abu Dhabi	20 November

In [ ]:
compound_map_2022 = {
    1:  {"SOFT": "C3", "MEDIUM": "C2", "HARD": "C1"},  # Bahrain
    2:  {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"},  # Saudi Arabia
    3:  {"SOFT": "C5", "MEDIUM": "C3", "HARD": "C2"},  # Australia
    4:  {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"},  # Emilia Romagna (Imola)
    5:  {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"},  # Miami
    6:  {"SOFT": "C3", "MEDIUM": "C2", "HARD": "C1"},  # Spain
    7:  {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},  # Monaco
    8:  {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},  # Azerbaijan
    9:  {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},  # Canada
    10: {"SOFT": "C3", "MEDIUM": "C2", "HARD": "C1"},  # Great Britain *
    11: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},  # Austria
    12: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"},  # France
    13: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"},  # Hungary
    14: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"},  # Belgium
    15: {"SOFT": "C3", "MEDIUM": "C2", "HARD": "C1"},  # Netherlands
    16: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"},  # Italy (Monza)
    17: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"},  # Singapore
    18: {"SOFT": "C3", "MEDIUM": "C2", "HARD": "C1"},  # Japan
    19: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"},  # USA
    20: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"},  # Mexico
    21: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"},  # Brazil
    22: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},  # Abu Dhabi
}

In [99]:
compound_map_2023 = {
    1: {"SOFT": "C3", "MEDIUM": "C2", "HARD": "C1"}, # Bahrain
    2: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"}, # Saudi Arabia
    3: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"}, # Australia
    4: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"}, # Azerbaijan
    5: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"}, # Miami, USA
    6: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"}, # Monaco
    7: {"SOFT": "C3", "MEDIUM": "C2", "HARD": "C1"}, # Spain
    8: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"}, # Canada
    9: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"}, # Austria
    10: {"SOFT": "C3", "MEDIUM": "C2", "HARD": "C1"},# United Kingdom
    11: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"}, # Hungary
    12: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"},# Belgium
    13: {"SOFT": "C3", "MEDIUM": "C2", "HARD": "C1"},# Netherlands
    14: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},# Italy
    15: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},# Singapore
    16: {"SOFT": "C3", "MEDIUM": "C2", "HARD": "C1"},# Japan
    17: {"SOFT": "C3", "MEDIUM": "C2", "HARD": "C1"},# Qatar
    18: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"},# United States, autin
    19: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},# Mexico
    20: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"},# Brazil
    21: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},# Las Vegas, USA
    22: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},# Abu Dhabi, UAE
}

In [96]:
compound_map_2024 = {
    1: {"SOFT": "C3", "MEDIUM": "C2", "HARD": "C1"}, # Bahrain
    2: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"}, # Saudi Arabia
    3: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"}, # Australia
    4: {"SOFT": "C3", "MEDIUM": "C2", "HARD": "C1"}, # Japan
    5: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"}, # China
    6: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"}, # Miami, USA
    7: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"}, # Emilia Romagna, Italy
    8: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"}, # Monaco
    9: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"}, # Canada
    10:{"SOFT": "C3", "MEDIUM": "C2", "HARD": "C1"}, # Spain
    11:{"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"}, # Austria
    12: {"SOFT": "C3", "MEDIUM": "C2", "HARD": "C1"},# United Kingdom
    13:{"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"}, # Hungary
    14: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"},# Belgium
    15: {"SOFT": "C3", "MEDIUM": "C2", "HARD": "C1"},# Netherlands
    16: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},# Italy
    17: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},# Azerbaijan
    18:{"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"}, # Singapore
    19: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"},# United States texas
    20: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},# Mexico
    21: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},# Brazil
    22:{"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"}, # Las Vegas, USA
    23: {"SOFT": "C3", "MEDIUM": "C2", "HARD": "C1"},# Qatar
    24:{"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"} # Abu Dhabi, UAE
}

In [95]:
compound_map_2025 = {
    1:  {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},  # Australia
    2:  {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"},  # China
    3:  {"SOFT": "C3", "MEDIUM": "C2", "HARD": "C1"},  # Japan
    4:  {"SOFT": "C3", "MEDIUM": "C2", "HARD": "C1"},  # Bahrain
    5:  {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},  # Saudi Arabia
    6:  {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},  # Miami, USA
    7:  {"SOFT": "C6", "MEDIUM": "C5", "HARD": "C4"},  # Emilia Romagna, Italy
    8:  {"SOFT": "C6", "MEDIUM": "C5", "HARD": "C4"},  # Monaco
    9:  {"SOFT": "C3", "MEDIUM": "C2", "HARD": "C1"},  # Spain
    10: {"SOFT": "C6", "MEDIUM": "C5", "HARD": "C4"},  # Canada
    11: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},  # Austria
    12: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"},  # United Kingdom
    13: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C1"},  # Belgium
    14: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},  # Hungary
    15: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"},  # Netherlands
    16: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},  # Italy
    17: {"SOFT": "C6", "MEDIUM": "C5", "HARD": "C4"},  # Azerbaijan
    18: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},  # Singapore
    19: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C1"},  # United States
    20: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C2"},  # Mexico
    21: {"SOFT": "C4", "MEDIUM": "C3", "HARD": "C2"},  # Brazil
    22: {"SOFT": "C5", "MEDIUM": "C4", "HARD": "C3"},  # Las Vegas, USA
}

In [117]:
sessions_df = pd.read_csv("race_f1_sessions25.csv")
sessions_df["Round"].max()

np.int64(22)

In [118]:
for round, compound_dict in compound_map_2025.items():
    sessions_df.drop(
        sessions_df[(sessions_df['Round'] == round) & (sessions_df['TrackStatus'].isin([4,5,6,7]))].index,
        inplace=True
    )
    mask = sessions_df['Round'] == round


    for old_c, new_c in compound_dict.items():
        mask = (sessions_df["Round"] == round) & (sessions_df['Compound'] == old_c)
        sessions_df.loc[mask, 'Compound'] = new_c

In [119]:
mask = (sessions_df['Compound'] == "INTERMEDIATE")
sessions_df.loc[mask, 'Compound'] = 'I'  

mask = (sessions_df['Compound'] == "WET")
sessions_df.loc[mask, 'Compound'] = 'W'

In [120]:
sessions_df[(sessions_df["Round"] == 2)]['Compound'].tail

<bound method NDFrame.tail of 927     C3
928     C3
929     C3
930     C3
931     C3
        ..
2367    C2
2368    C2
2369    C2
2370    C2
2371    C2
Name: Compound, Length: 1445, dtype: object>

In [121]:
sessions_df[sessions_df["TrackStatus"] == 7]

Empty DataFrame
Columns: [Time, Driver, DriverNumber, LapTime, LapNumber, Stint, PitOutTime, PitInTime, Sector1Time, Sector2Time, Sector3Time, Sector1SessionTime, Sector2SessionTime, Sector3SessionTime, SpeedI1, SpeedI2, SpeedFL, SpeedST, IsPersonalBest, Compound, TyreLife, FreshTyre, Team, LapStartTime, LapStartDate, TrackStatus, Position, Deleted, DeletedReason, FastF1Generated, IsAccurate, Year, Round, Session]
Index: []

[0 rows x 34 columns]

In [122]:
sessions_df[sessions_df["Compound"] == "C5"]

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,Round,Session
5471,0 days 01:40:14.305000,NOR,4,NaN,15.0,2.0,0 days 01:37:39.541000,NaN,0 days 00:01:06.040000,0 days 00:01:03.781000,...,2025-05-03 16:54:41.172,24,1.0,False,NaN,False,False,2025,6,Sprint
5474,0 days 01:47:18.302000,NOR,4,0 days 00:02:17.649000,18.0,2.0,NaN,NaN,0 days 00:00:49.082000,0 days 00:00:49.066000,...,2025-05-03 17:02:20.400,41,1.0,False,NaN,False,False,2025,6,Sprint
5504,0 days 01:34:29.738000,HAM,44,0 days 00:01:55.804000,12.0,2.0,0 days 01:32:50.881000,NaN,0 days 00:00:51.142000,0 days 00:00:37.303000,...,2025-05-03 16:49:53.681,12,12.0,False,NaN,False,False,2025,6,Sprint
5505,0 days 01:36:06.106000,HAM,44,0 days 00:01:36.368000,13.0,2.0,NaN,NaN,0 days 00:00:33.165000,0 days 00:00:36.281000,...,2025-05-03 16:51:49.485,1,6.0,False,NaN,False,True,2025,6,Sprint
5506,0 days 01:37:45.407000,HAM,44,0 days 00:01:39.301000,14.0,2.0,NaN,NaN,0 days 00:00:32.049000,0 days 00:00:35.314000,...,2025-05-03 16:53:25.853,124,3.0,False,NaN,False,False,2025,6,Sprint
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23657,0 days 02:32:37.496000,BEA,87,0 days 00:01:22.733000,69.0,3.0,NaN,NaN,0 days 00:00:28.738000,0 days 00:00:31.914000,...,2025-10-26 21:37:23.538,12,4.0,False,NaN,False,True,2025,20,Race
23658,0 days 02:34:17.041000,BEA,87,0 days 00:01:39.545000,70.0,3.0,NaN,NaN,0 days 00:00:28.277000,0 days 00:00:43.902000,...,2025-10-26 21:38:46.271,26,4.0,False,NaN,False,False,2025,20,Race
23659,0 days 02:35:46.905000,BEA,87,0 days 00:01:29.864000,71.0,3.0,NaN,NaN,0 days 00:00:37.182000,0 days 00:00:31.814000,...,2025-10-26 21:40:25.816,671,4.0,False,NaN,False,False,2025,20,Race
25455,0 days 00:59:32.945000,ANT,12,0 days 00:01:51.048000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:34.380000,...,2025-11-23 04:04:08.478,12,14.0,False,NaN,False,False,2025,22,Race
25456,0 days 01:01:35.518000,ANT,12,0 days 00:02:02.573000,2.0,1.0,NaN,0 days 01:01:32.526000,0 days 00:00:29.681000,0 days 00:00:34.477000,...,2025-11-23 04:05:59.796,126,14.0,False,NaN,False,False,2025,22,Race

In [123]:

sessions_df.to_csv("race_f1_sessions25_cleaned.csv", index=False)